### List site template styles
GET {{baseUrl}}/api/index.php/v1/templates/styles/site
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### List site template styles, with filters
# Filters:
# - filter[search]    string  Search by style title
# - filter[template]  string  Template name
GET {{baseUrl}}/api/index.php/v1/templates/styles/site?filter[template]=cassiopeia
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### Get site template style data
GET {{baseUrl}}/api/index.php/v1/templates/styles/site/10
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### Create site template style
POST {{baseUrl}}/api/index.php/v1/templates/styles/site
Authorization: Bearer {{token}}
Accept: application/vnd.api+json
Content-Type: application/json

{
	"title": "Cassiopeia - Custom",
	"template": "cassiopeia",
	"home": false
}

### Update site template style
PATCH {{baseUrl}}/api/index.php/v1/templates/styles/site/10
Authorization: Bearer {{token}}
Accept: application/vnd.api+json
Content-Type: application/json

{
	"title": "Cassiopeia - Updated"
}

### Delete site template style
DELETE {{baseUrl}}/api/index.php/v1/templates/styles/site/10
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### List administrator template styles
GET {{baseUrl}}/api/index.php/v1/templates/styles/administrator
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### Get administrator template style data
GET {{baseUrl}}/api/index.php/v1/templates/styles/administrator/1
Authorization: Bearer {{token}}
Accept: application/vnd.api+json

### Create administrator template style
POST {{baseUrl}}/api/index.php/v1/templates/styles/administrator
Authorization: Bearer {{token}}
Accept: application/vnd.api+json
Content-Type: application/json

{
	"title": "Atum - Custom",
	"template": "atum",
	"home": false
}

### Update administrator template style
PATCH {{baseUrl}}/api/index.php/v1/templates/styles/administrator/1
Authorization: Bearer {{token}}
Accept: application/vnd.api+json
Content-Type: application/json

{
	"title": "Atum - Updated"
}

### Delete administrator template style
DELETE {{baseUrl}}/api/index.php/v1/templates/styles/administrator/1
Authorization: Bearer {{token}}
Accept: application/vnd.api+json
